/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as AtajosRouteImport } from './routes/atajos'
import { Route as CierreRouteImport } from './routes/cierre'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as FacturacionRouteImport } from './routes/facturacion'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as VentaRouteImport } from './routes/venta'
import { Route as ApiVersionRouteImport } from './routes/api/version'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AtajosRoute = AtajosRouteImport.update({
  id: '/atajos',
  path: '/atajos',
  getParentRoute: () => rootRouteImport,
} as any)
const CierreRoute = CierreRouteImport.update({
  id: '/cierre',
  path: '/cierre',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionRoute = FacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const VentaRoute = VentaRouteImport.update({
  id: '/venta',
  path: '/venta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/atajos': typeof AtajosRoute
  '/cierre': typeof CierreRoute
  '/clientes': typeof ClientesRoute
  '/facturacion': typeof FacturacionRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/pedidos': typeof PedidosRoute
  '/venta': typeof VentaRoute
  '/api/version': typeof ApiVersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/atajos': typeof AtajosRoute
  '/cierre': typeof CierreRoute
  '/clientes': typeof ClientesRoute
  '/facturacion': typeof FacturacionRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/pedidos': typeof PedidosRoute
  '/venta': typeof VentaRoute
  '/api/version': typeof ApiVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/atajos': typeof AtajosRoute
  '/cierre': typeof CierreRoute
  '/clientes': typeof ClientesRoute
  '/facturacion': typeof FacturacionRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/pedidos': typeof PedidosRoute
  '/venta': typeof VentaRoute
  '/api/version': typeof ApiVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/atajos'
    | '/cierre'
    | '/clientes'
    | '/facturacion'
    | '/inventario'
    | '/login'
    | '/pedidos'
    | '/venta'
    | '/api/version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/atajos'
    | '/cierre'
    | '/clientes'
    | '/facturacion'
    | '/inventario'
    | '/login'
    | '/pedidos'
    | '/venta'
    | '/api/version'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/atajos'
    | '/cierre'
    | '/clientes'
    | '/facturacion'
    | '/inventario'
    | '/login'
    | '/pedidos'
    | '/venta'
    | '/api/version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  AtajosRoute: typeof AtajosRoute
  CierreRoute: typeof CierreRoute
  ClientesRoute: typeof ClientesRoute
  FacturacionRoute: typeof FacturacionRoute
  InventarioRoute: typeof InventarioRoute
  LoginRoute: typeof LoginRoute
  PedidosRoute: typeof PedidosRoute
  VentaRoute: typeof VentaRoute
  ApiVersionRoute: typeof ApiVersionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atajos': {
      id: '/atajos'
      path: '/atajos'
      fullPath: '/atajos'
      preLoaderRoute: typeof AtajosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cierre': {
      id: '/cierre'
      path: '/cierre'
      fullPath: '/cierre'
      preLoaderRoute: typeof CierreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion': {
      id: '/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof FacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venta': {
      id: '/venta'
      path: '/venta'
      fullPath: '/venta'
      preLoaderRoute: typeof VentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  AtajosRoute: AtajosRoute,
  CierreRoute: CierreRoute,
  ClientesRoute: ClientesRoute,
  FacturacionRoute: FacturacionRoute,
  InventarioRoute: InventarioRoute,
  LoginRoute: LoginRoute,
  PedidosRoute: PedidosRoute,
  VentaRoute: VentaRoute,
  ApiVersionRoute: ApiVersionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
